<?php

declare(strict_types=1);

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

/**
 * Adds the same CORS policy to every API endpoint.
 *
 * Keeping this behavior in an event subscriber avoids repeating headers in each
 * controller and also covers responses generated by security or error handling.
 */
final class CorsSubscriber implements EventSubscriberInterface
{
    private const API_PATH_PREFIX = '/api';
    private const ALLOWED_ORIGIN = '*';
    private const ALLOWED_METHODS = 'GET, POST, OPTIONS';
    private const ALLOWED_HEADERS = 'Authorization, Content-Type, Accept';

    public static function getSubscribedEvents(): array
    {
        return [
            // Run before routing and the security firewall so preflight requests do not require a JWT.
            KernelEvents::REQUEST => ['onKernelRequest', 2048],
            KernelEvents::RESPONSE => 'onKernelResponse',
        ];
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        $request = $event->getRequest();
        if (!$this->isApiPath($request->getPathInfo()) || !$request->isMethod('OPTIONS')) {
            return;
        }

        // A preflight request only negotiates browser permissions and has no response body.
        $response = new Response(status: Response::HTTP_NO_CONTENT);
        $this->addCorsHeaders($response);
        $event->setResponse($response);
    }

    public function onKernelResponse(ResponseEvent $event): void
    {
        if (!$event->isMainRequest() || !$this->isApiPath($event->getRequest()->getPathInfo())) {
            return;
        }

        $this->addCorsHeaders($event->getResponse());
    }

    private function isApiPath(string $path): bool
    {
        return $path === self::API_PATH_PREFIX || str_starts_with($path, self::API_PATH_PREFIX.'/');
    }

    private function addCorsHeaders(Response $response): void
    {
        $response->headers->set('Access-Control-Allow-Origin', self::ALLOWED_ORIGIN);
        $response->headers->set('Access-Control-Allow-Methods', self::ALLOWED_METHODS);
        $response->headers->set('Access-Control-Allow-Headers', self::ALLOWED_HEADERS);
        $response->headers->set('Access-Control-Max-Age', '3600');
    }
}
